#http://localhost:8888/aplication/default
#http://localhost:8888/aplication/dev
#http://localhost:8888/aplication/prod

#Prod profili için genel ayarlar



  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/eCommerce
      username: postgres
      password: 12345

  logging:
    level:
      root: WARN

#ÜRETİM ORTAMINA ÖZGÜ DİĞER AYARLAR ÖRNEĞİN GÜVENLİK YAPILANDIRMALARI