#http://localhost:8888/aplication/default
#http://localhost:8888/aplication/dev
#http://localhost:8888/aplication/prod

#Tüm profiller için genel ayarlar
server:
  port: 8888

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/eCommerce
      username: postgres
      password: 12345
      jpa:
        hibernate:
          ddl-auto: update
          show-sql: true

          logging:
            level:
              root: INFO

   # Genel ayarlar burda bulunur örneğin ortak kullanılan  servisler ve apı ayarları