#http://localhost:8888/aplication/default
#http://localhost:8888/aplication/dev
#http://localhost:8888/aplication/prod

#Dev profili için genel ayarlar

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/eCommerce
      username: postgres
      password: 12345

  logging:
    level:
     root: DEBUG

#Geliştirme ortamına özgü diğer ayarlar örneğin daha detaylı hata ayıklama  bilgileri veya  test veritabanı bağlantıları

